# Generated by Django 5.2.3 on 2025-06-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('province_code', models.IntegerField()),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('registration_num', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('standard', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('subdistrict', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('factory_phone_number', models.TextField(blank=True, null=True)),
                ('owner_name', models.TextField(blank=True, null=True)),
                ('owner_address', models.TextField(blank=True, null=True)),
                ('owner_phone_number', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('hp', models.FloatField(blank=True, null=True)),
                ('capital', models.FloatField(blank=True, null=True)),
                ('worker', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactoryTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('registration_num', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('standard', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('subdistrict', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('factory_phone_number', models.TextField(blank=True, null=True)),
                ('owner_name', models.TextField(blank=True, null=True)),
                ('owner_address', models.TextField(blank=True, null=True)),
                ('owner_phone_number', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('hp', models.FloatField(blank=True, null=True)),
                ('capital', models.FloatField(blank=True, null=True)),
                ('worker', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factory_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactoryTemp1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('registration_num', models.TextField(blank=True, null=True)),
                ('type', models.FloatField(blank=True, null=True)),
                ('standard', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('subdistrict', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('factory_phone_number', models.TextField(blank=True, null=True)),
                ('owner_name', models.TextField(blank=True, null=True)),
                ('owner_address', models.TextField(blank=True, null=True)),
                ('owner_phone_number', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('hp', models.FloatField(blank=True, db_column='HP', null=True)),
                ('capital', models.FloatField(blank=True, null=True)),
                ('worker', models.IntegerField(blank=True, null=True)),
                ('lat', models.IntegerField(blank=True, null=True)),
                ('lng', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factory_temp (1)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('district_code', models.IntegerField()),
                ('is_island', models.IntegerField()),
            ],
            options={
                'db_table': 'subdistrict',
                'managed': False,
            },
        ),
    ]
