# Generated by Django 5.2.4 on 2025-07-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.TextField(blank=True, null=True)),
                ('store_id', models.IntegerField(blank=True, null=True)),
                ('branch_type', models.TextField(blank=True, null=True)),
                ('format', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('subdistrict', models.TextField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_store3',
                'managed': False,
            },
        ),
    ]
