# Generated by Django 5.2.4 on 2025-07-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('province_code', models.IntegerField()),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('district_code', models.IntegerField()),
                ('is_island', models.IntegerField()),
            ],
            options={
                'db_table': 'subdistrict',
                'managed': False,
            },
        ),
    ]
